---
title: "Files formats"
output:
  html_document: default
  html_notebook: default
---

## Getting data

Download all datasets from  <https://www.kaggle.com/c/competitive-data-science-predict-future-sales/data> into directory `future_sales_data` and uznip it.

## Access to data from spark


```{r}

library(sparklyr)
library(dplyr)
sc <- spark_connect(master = "local")
```

```{r}
sales_sdf <- spark_read_csv(sc, "sales", "../future_sales_data/sales_train.csv.gz")

sales_sdf %>%
  mutate(dt=to_timestamp(unix_timestamp(date, 'dd.MM.yyyy'))) %>%
  mutate(year=year(dt), month=month(dt)) %>%
  select(-dt) ->
  sales_sdf

sales_sdf %>%
  spark_write_parquet(
    "../future_sales_data/sales_train.parquet",
    partition_by = c("shop_id", "year", "month"))

sales_sdf %>% count
```

```{r}
sales_sdf <- spark_read_csv(sc, "sales", "../future_sales_data/sales_train.parquet/shop_id\\=0/year\\=2013/month\\=1/")
```


## Parquet and buckets

```{r}
mtcars_tbl <- copy_to(sc, mtcars)

# transform our data set, and then partition into 'training', 'test'
partitions <- mtcars_tbl %>%
  filter(hp >= 100) %>%
  mutate(cyl8 = cyl == 8) %>%
  sdf_partition(training = 0.5, test = 0.5, seed = 1099)


shops <-
  sales_sdf %>%
  select('shop_id') %>%
  distinct %>%
  collect

sales_sdf %>%
  withColumn("dt", to_timestamp(unix_timestamp(.$date, 'dd.MM.yyyy'))) ->
  sales_sdf

sales_sdf %>%
  select(alias(year(.$dt), "shop_id")) %>%
  distinct %>%
  collect ->
  years

```


```{r}
distinct_dates <-
  sales_sdf %>%
  select(alias(to_timestamp(unix_timestamp(.$date, 'dd.MM.yyyy')), "dt")) %>%
  distinct

distinct_dates %>%
  select(
    alias(year(.$dt), 'year'),
    alias(month(.$dt), 'month'),
    alias(dayofmonth(.$dt), 'day')
  ) %>%
  collect ->
  dates_df

dates_df %>%
  head
```

```{r}
get_dates <- function(row) {
  print(row)
  
}
```

```{r}
separated_date <-
  sales_sdf %>%
  select(alias(split_string(sales_sdf$date, "\\."), "dates"))
```

```{r}
separated_date %>%
  select(separated_date$dates$1) %>%
  head
```

```{r}
schema <- structType(structField("a", "integer")
)
dapply(
  sales_sdf,
  function(x) {
    x$item_cnt_day
  },
  schema) %>%
  head

```

```{r}
sales_sdf %>%
  saveAsParquetFile("../future_sales_data/sales_train.parquet")
```
